name: "Build Modpack"

on:
  push:
    branches:
      - 'main'

jobs:
  build-modpack:
    name: Build Minecraft Modpack
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup pakku
        run: |
          wget https://github.com/juraj-hrivnak/Pakku/releases/download/v1.0.0/pakku.jar

      - name: Set pakku credentials
        run: java -jar pakku.jar credentials set --cf-api-key ${cf_api_key}
        env: # Or as an environment variable
          cf_api_key: ${{ secrets.CURSEFORGE_API_KEY }}

      - name: Export modpack
        run: java -jar pakku.jar export

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "release.tar.gz,foo/*.txt"
      #     bodyFile: "body.md"

      # Unzip the build modpack files
      - name: Extract serverpack
        uses: ihiroky/extract-action@v1
        with:
          file_path: ./build/serverpack/Blake Server-0.0.1.zip
          extract_dir: ./serverpack

      - name: Extract curseforge
        uses: ihiroky/extract-action@v1
        with:
          file_path: ./build/curseforge/Blake Server-0.0.1.zip
          extract_dir: ./curseforge

      # Upload the build artifacts
      - name: Upload Curseforge Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: curseforge-artifact
          path: ./curseforge/
          retention-days: 5

      - name: Upload Server Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: server-artifact
          path: ./serverpack/
          retention-days: 5
